import type {NextPage} from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import {useRouter} from 'next/router';
import {Button} from '@mui/material';

const buttonStyles = {
    mt: '50px', fontSize: '40px', padding: '20px 70px'
}

const Home: NextPage = () => {
    const router = useRouter()
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>Welcome to CredibleMind</h1>
                <Button onClick={() => {
                    router.push('/news')
                }} sx={buttonStyles}>GO TO NEWS</Button>
            </main>
        </div>
    );
};

export default Home;
